/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTemplatesGavetaRouteImport } from './routes/_authenticated/templates-gaveta'
import { Route as AuthenticatedTemplatesFuracaoRouteImport } from './routes/_authenticated/templates-furacao'
import { Route as AuthenticatedPuxadoresRouteImport } from './routes/_authenticated/puxadores'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedOrlasRouteImport } from './routes/_authenticated/orlas'
import { Route as AuthenticatedModulosRouteImport } from './routes/_authenticated/modulos'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedFerragensRouteImport } from './routes/_authenticated/ferragens'
import { Route as AuthenticatedDefinicoesRouteImport } from './routes/_authenticated/definicoes'
import { Route as AuthenticatedBrocasRouteImport } from './routes/_authenticated/brocas'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAmbientesRouteImport } from './routes/_authenticated/ambientes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesGavetaRoute =
  AuthenticatedTemplatesGavetaRouteImport.update({
    id: '/templates-gaveta',
    path: '/templates-gaveta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesFuracaoRoute =
  AuthenticatedTemplatesFuracaoRouteImport.update({
    id: '/templates-furacao',
    path: '/templates-furacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPuxadoresRoute = AuthenticatedPuxadoresRouteImport.update({
  id: '/puxadores',
  path: '/puxadores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrlasRoute = AuthenticatedOrlasRouteImport.update({
  id: '/orlas',
  path: '/orlas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulosRoute = AuthenticatedModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFerragensRoute = AuthenticatedFerragensRouteImport.update({
  id: '/ferragens',
  path: '/ferragens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDefinicoesRoute = AuthenticatedDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrocasRoute = AuthenticatedBrocasRouteImport.update({
  id: '/brocas',
  path: '/brocas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmbientesRoute = AuthenticatedAmbientesRouteImport.update({
  id: '/ambientes',
  path: '/ambientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ambientes': typeof AuthenticatedAmbientesRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/brocas': typeof AuthenticatedBrocasRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/ferragens': typeof AuthenticatedFerragensRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/modulos': typeof AuthenticatedModulosRoute
  '/orlas': typeof AuthenticatedOrlasRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/puxadores': typeof AuthenticatedPuxadoresRoute
  '/templates-furacao': typeof AuthenticatedTemplatesFuracaoRoute
  '/templates-gaveta': typeof AuthenticatedTemplatesGavetaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ambientes': typeof AuthenticatedAmbientesRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/brocas': typeof AuthenticatedBrocasRoute
  '/definicoes': typeof AuthenticatedDefinicoesRoute
  '/ferragens': typeof AuthenticatedFerragensRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/modulos': typeof AuthenticatedModulosRoute
  '/orlas': typeof AuthenticatedOrlasRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/puxadores': typeof AuthenticatedPuxadoresRoute
  '/templates-furacao': typeof AuthenticatedTemplatesFuracaoRoute
  '/templates-gaveta': typeof AuthenticatedTemplatesGavetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ambientes': typeof AuthenticatedAmbientesRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/brocas': typeof AuthenticatedBrocasRoute
  '/_authenticated/definicoes': typeof AuthenticatedDefinicoesRoute
  '/_authenticated/ferragens': typeof AuthenticatedFerragensRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/modulos': typeof AuthenticatedModulosRoute
  '/_authenticated/orlas': typeof AuthenticatedOrlasRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/puxadores': typeof AuthenticatedPuxadoresRoute
  '/_authenticated/templates-furacao': typeof AuthenticatedTemplatesFuracaoRoute
  '/_authenticated/templates-gaveta': typeof AuthenticatedTemplatesGavetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ambientes'
    | '/biblioteca'
    | '/brocas'
    | '/definicoes'
    | '/ferragens'
    | '/materiais'
    | '/modulos'
    | '/orlas'
    | '/projetos'
    | '/puxadores'
    | '/templates-furacao'
    | '/templates-gaveta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ambientes'
    | '/biblioteca'
    | '/brocas'
    | '/definicoes'
    | '/ferragens'
    | '/materiais'
    | '/modulos'
    | '/orlas'
    | '/projetos'
    | '/puxadores'
    | '/templates-furacao'
    | '/templates-gaveta'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ambientes'
    | '/_authenticated/biblioteca'
    | '/_authenticated/brocas'
    | '/_authenticated/definicoes'
    | '/_authenticated/ferragens'
    | '/_authenticated/materiais'
    | '/_authenticated/modulos'
    | '/_authenticated/orlas'
    | '/_authenticated/projetos'
    | '/_authenticated/puxadores'
    | '/_authenticated/templates-furacao'
    | '/_authenticated/templates-gaveta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates-gaveta': {
      id: '/_authenticated/templates-gaveta'
      path: '/templates-gaveta'
      fullPath: '/templates-gaveta'
      preLoaderRoute: typeof AuthenticatedTemplatesGavetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates-furacao': {
      id: '/_authenticated/templates-furacao'
      path: '/templates-furacao'
      fullPath: '/templates-furacao'
      preLoaderRoute: typeof AuthenticatedTemplatesFuracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/puxadores': {
      id: '/_authenticated/puxadores'
      path: '/puxadores'
      fullPath: '/puxadores'
      preLoaderRoute: typeof AuthenticatedPuxadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orlas': {
      id: '/_authenticated/orlas'
      path: '/orlas'
      fullPath: '/orlas'
      preLoaderRoute: typeof AuthenticatedOrlasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulos': {
      id: '/_authenticated/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof AuthenticatedModulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferragens': {
      id: '/_authenticated/ferragens'
      path: '/ferragens'
      fullPath: '/ferragens'
      preLoaderRoute: typeof AuthenticatedFerragensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definicoes': {
      id: '/_authenticated/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof AuthenticatedDefinicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brocas': {
      id: '/_authenticated/brocas'
      path: '/brocas'
      fullPath: '/brocas'
      preLoaderRoute: typeof AuthenticatedBrocasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ambientes': {
      id: '/_authenticated/ambientes'
      path: '/ambientes'
      fullPath: '/ambientes'
      preLoaderRoute: typeof AuthenticatedAmbientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAmbientesRoute: typeof AuthenticatedAmbientesRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedBrocasRoute: typeof AuthenticatedBrocasRoute
  AuthenticatedDefinicoesRoute: typeof AuthenticatedDefinicoesRoute
  AuthenticatedFerragensRoute: typeof AuthenticatedFerragensRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedModulosRoute: typeof AuthenticatedModulosRoute
  AuthenticatedOrlasRoute: typeof AuthenticatedOrlasRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedPuxadoresRoute: typeof AuthenticatedPuxadoresRoute
  AuthenticatedTemplatesFuracaoRoute: typeof AuthenticatedTemplatesFuracaoRoute
  AuthenticatedTemplatesGavetaRoute: typeof AuthenticatedTemplatesGavetaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAmbientesRoute: AuthenticatedAmbientesRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedBrocasRoute: AuthenticatedBrocasRoute,
  AuthenticatedDefinicoesRoute: AuthenticatedDefinicoesRoute,
  AuthenticatedFerragensRoute: AuthenticatedFerragensRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedModulosRoute: AuthenticatedModulosRoute,
  AuthenticatedOrlasRoute: AuthenticatedOrlasRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedPuxadoresRoute: AuthenticatedPuxadoresRoute,
  AuthenticatedTemplatesFuracaoRoute: AuthenticatedTemplatesFuracaoRoute,
  AuthenticatedTemplatesGavetaRoute: AuthenticatedTemplatesGavetaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
